import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
    title: "Online News",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-gray-50">
                <main className="bg-white max-w-7xl mx-auto flex flex-col min-h-screen ring-1 ring-gray-200 px-10 py-8">
                    <Navbar />
                    {children}
                </main>
            </body>
        </html>
    );
}
